---
- name: Install and Deploy Docker application 
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        update_cache: yes

    - name: Pull Docker image
      docker_image:
        name: chaddekiran/sms_spam_detection_ml_model
        tag: latest

    - name: Run Docker container
      docker_container:
        name: springboot_app
        image: chaddekiran/sms_spam_detection_ml_model:latest
        ports:
          - "80:8501" 
