---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sms_spam_detector
    k8s-app: sms_spam_detector
  name: sms_spam_detector
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8501
  type: LoadBalancer
  selector:
    app: sms_spam_detector